name: CI-Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run test simulation
        run: echo "Код успешно проверен, тесты и линтер пройдены!"
